# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - delena-kingmaker-pf2-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

#      - name: Build with Maven
#        run: mvn clean install

# Copied from Vialeea
      - name: Build with Gradle
        run: |
          cd Application
          chmod +x gradlew
          ./gradlew build test bootwar
          cp build/libs/ROOT.war build/libs/app.jar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0423B8BE83444EE0960A211FC2A52054 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61D1717484284DC9914103FD3AB34CAE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_595ACCFF5D6A46519DC07B9D89D4A5A4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'delena-kingmaker-pf2-backend'
          slot-name: 'Production'
          package: '*.jar'
          